name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true

    - name: Update Bundler
      run: gem install bundler -v 2.3.26

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        # Use the updated bundler version to install gems
        bundle _2.3.26_ install

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "NO_PUSH=--no-push" >> $GITHUB_ENV
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

    - name: Deploy website 
      run: yes | bash bin/deploy --verbose $NO_PUSH --src $SRC_BRANCH --deploy $DEPLOY_BRANCH
